accounts:
  - name: alice
    coins: ['200000000usln']
  - name: bob
    coins: ['100000000usln']
validator:
  name: alice
  staked: '100000000usln'
client:
  openapi:
    path: 'docs/static/openapi.yml'
  vuex:
    path: 'vue/src/store'
faucet:
  name: bob
  coins: ['100000usln']
genesis:
  app_state:
    bank:      
      denom_metadata:
        - description: "The native staking token of your blockchain"
          display: "sln"
          base: "usln"
          name: "Selenian"
          symbol: "SLN"
          denom_units:
            - denom: "usln"
              exponent: "0"
            - denom: "sln"
              exponent: "6"
    staking:
      params:
        bond_denom: 'usln'

